services:
  frontend:
    build: ./frontend
    container_name: ps-gold-frontend
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 100M

  backend:
    build: ./backend
    container_name: ps-gold-backend
    restart: always
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/prisma/dev.db
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3000
    expose:
      - "3000"
    volumes:
      - ./backend/prisma:/app/prisma
    deploy:
      resources:
        limits:
          memory: 300M
        reservations:
          memory: 150M

volumes:
  mongodb_data:
