services:
  frontend:
    build: ./frontend
    container_name: ps-gold-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 100M

  backend:
    build: ./backend
    container_name: ps-gold-backend
    restart: always
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/ps-gold
      - JWT_SECRET=your_jwt_secret_here
      - COOKIE_SECRET=your_cookie_secret_here
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    deploy:
      resources:
        limits:
          memory: 300M
        reservations:
          memory: 150M

  mongodb:
    image: mongo:latest
    container_name: ps-gold-mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          memory: 400M
        reservations:
          memory: 200M

volumes:
  mongodb_data:
