services:
  frontend:
    build: ./frontend
    container_name: ps-gold-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 100M

  backend:
    build: ./backend
    container_name: ps-gold-backend
    restart: always
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/prisma/dev.db
      - JWT_SECRET=your_jwt_secret_here
      - COOKIE_SECRET=your_cookie_secret_here
    ports:
      - "3000:3000"
    volumes:
      - ./backend/prisma:/app/prisma
    deploy:
      resources:
        limits:
          memory: 300M
        reservations:
          memory: 150M

volumes:
  mongodb_data:
